### ISSUE TITLE
go-ipfs sometimes closes the stream preemptively

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-http-client#339] opened 2016-08-10 08:11 UTC
From: https://github.com/ipfs/js-ipfs-api/pull/337#issuecomment-238541189

---

Ok, I thought I had fixed the adding dirs on the browser, but then realised that there is a bug that only happens sometimes (like 1 out of 20), where we don't receive all the hashes for the files added.

I thought this could be an js-ipfs-api problem, but further testing (and some fixes) narrowed down the problem to how go-ipfs is responding, even when requests are 100% the same, the response may differ.

The failing failing test is: https://github.com/ipfs/interface-ipfs-core/blob/feat/ipfs.files.get/src/files.js#L113-L143 (again: just fails in the browser and some of the times)

(left -> success; center -> fails)
![image](https://cloud.githubusercontent.com/assets/1211152/17516545/d202fbe4-5e36-11e6-9053-c715442b6a17.png)

[Full request + response of a Success](https://github.com/ipfs/js-ipfs-api/files/408905/success.txt)
[Full request + response of a Failure](https://github.com/ipfs/js-ipfs-api/files/408906/failure.txt)
[wireshark pcap (filter for HTTP and then look for the POST /add](https://ipfs.io/ipfs/Qmctcru7zYWrkHsfBQHFN7M6e6EsNbfGPMVcarooV1Fmod)
## How to reproduce

``` sh
> git clone git@github.com:ipfs/interface-ipfs-core.git -b feat/ipfs.files.get 
> cd interface-ipfs-core
> npm i && npm run build && npm link
> cd ..
> git clone git@github.com:ipfs/js-ipfs-api.git -b feat/ipfs.files.get
> cd js-ipfs-api 
> npm i && npm link interface-ipfs-core
> npm run test:browser # repeat this one till it fails
```

**Comment by whyrusleeping** [comment] 2016-08-10 16:46
@diasdavid @dignifiedquire could you find a way to reproduce this with a simple curl command? I guess i'm just not very good at javascript but i have trouble even getting these tests to run, consistently hitting new and exciting problems.

**Comment by diasdavid** [comment] 2016-08-10 17:05
After we talked and you getting the test to run, are you still getting that issue?

**Comment by whyrusleeping** [comment] 2016-08-10 17:12
apparently i just needed to rerun it a few times for the tests to run. I was having issues with karma and chrome, but a few more tries and it started running the tests.

**Comment by whyrusleeping** [comment] 2016-08-11 18:25
A relevant note: this has only been reproduced in the browser testing.

**Comment by whyrusleeping** [comment] 2016-08-18 23:26
might be related to: https://github.com/ipfs/go-ipfs/issues/2112

Which i can only reproduce using ipfs 0.4.2 or earlier.

**Comment by diasdavid** [comment] 2016-08-25 04:19
Not being able to reproduce with 0.4.3 :)

**Comment by diasdavid** [comment] 2016-08-25 04:20
Still seeing the same problem in 0.4.3.

**Comment by whyrusleeping** [comment] 2016-08-25 16:12
@diasdavid thanks for checking.

**Comment by diasdavid** [comment] 2016-08-29 14:56
@whyrusleeping anything else I can do to help with this bug?

**Comment by diasdavid** [comment] 2016-09-07 20:06
Any developments?

**Comment by diasdavid** [comment] 2016-12-05 04:03
@keks, @whyrusleeping mentioned that you found an issue on the http-api that might be the root of this problem (about closing the multipart stream), does it ring a bell?

**Comment by diasdavid** [comment] 2017-11-17 10:59
Seeing positive results in https://github.com/ipfs/js-ipfs-api/pull/619

**Comment by diasdavid** [comment] 2017-11-17 19:08
Spoke too soon. This is still a thing, although less frequently!

**Comment by GTRI-nathan** [comment] 2018-01-17 19:33
I think I might be running into this error, but it happens every time for me. I made a quick and dirty paired down testcase here: https://github.com/GTRI-nathan/js-ipfs-api-test
Does this seem to be the same thing or should I open a new issue?

Thanks!

**Comment by julientregoat** [comment] 2018-03-19 16:36
Can't tell if this was related, but --
I was trying to add files in the API as an array of objects. Following the example from [the IPFS API docs](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#add)

`const files = [
  {
    path: '/tmp/myfile.txt',
    content: (Buffer or Readable stream)
  }
]

ipfs.files.add(files, function (err, files) {
  // 'files' will be an array of objects containing paths and the multihashes of the files added
})`

I tried and failed to upload files as a group. This is how I tried
```
  for(let i=0; i < fileCount; i++){
      let reader = new FileReader();
      let file = this.props.uploader.files[i]
      // might need to get DIR path first before uploading files?
      let path = "/" + release_title + "/" + file.name

      reader.onloadend = () => {
        buffer = Buffer.from(reader.result)
        files.push({path: path, content: buffer})
        // ipfs.files.mkdir("/" + release_title)
        ipfs.files.write(path, buffer, {create: true}).then(console.log)
      }
      let buffer = reader.readAsArrayBuffer(file)
    }
`

**Comment by julientregoat** [comment] 2018-03-19 16:47
I think the same was happening to me. When I try to create a directory of files using `ipfs.files.add([{path: /dir}, {path: /dir/filename.type}])`, it only creates the directory, then stops at the next file.

I get the error from my daemon'expected at least one child dir'. But outside of an array of objects, it's working completely fine. Not sure if this is the same problem but it seemed similar since it would just stop and not return any errors.

**Comment by achingbrain** [comment] 2020-03-09 14:16
This issue is very stale so I'm going to close it.  Tests were previously skipped for this PR but aren't any more.  Please open a new issue against [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs) if you still see it.

**Closed by achingbrain** 2020-03-09 14:16 UTC
Labels: P1 - High, bug, difficulty:hard, help wanted, ready
