### ISSUE TITLE
.files .add a BIG buffer with progress enabled core test is flaky

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-http-client#726] opened 2018-03-29 13:02 UTC
The interface core test .files .add a BIG buffer with progress enabled core test is flaky. It fails a lot on CI. I was able to reproduce it locally a few times (not always) with running:

    cpulimit -l 80 -- node ./node_modules/.bin/aegir test -t browser --files test/core/bitswap.spec.js test/core/bootstrap.spec.js test/core/config.spec.js test/core/create-node.spec.js test/core/files-sharding.spec.js test/core/init.spec.js test/core/interface/config.js test/core/interface/files.js

The interesting part is that this test doesn't return the added data (it's an empty array) but also no error.

**Comment by JonKrone** [comment] 2018-04-03 20:04
Possible case: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1045/16/pipeline/

**Comment by diasdavid** [comment] 2018-04-04 21:15
@dryajov mind checking ?

**Comment by dryajov** [comment] 2018-04-04 23:32
checking 👍

**Comment by alanshaw** [comment] 2018-05-11 14:13
@dryajov did you find anything?

**Comment by dryajov** [comment] 2018-05-11 14:51
I don't think I was able to reproduce the issue locally, and moved on to serving else. I'll try one more time and report back here.

**Comment by alanshaw** [comment] 2018-05-15 10:26
related to #748?

**Comment by achingbrain** [comment] 2020-03-09 14:10
This test hasn't been flaky in a while and the code behind it has changed significantly since this issue was opened.  We'll keep an eye on it but am closing this for now.

**Closed by achingbrain** 2020-03-09 14:10 UTC
Labels: bug, difficulty:hard, ready
