### ISSUE TITLE
IPFS filestore support

### ISSUE THREAD

**Issue by obo20** [ipfs/js-ipfs-http-client#1163] opened 2019-03-01 21:16 UTC
There doesn't seem to be support for the --nocopy flag when adding files via any of the ipfs add endpoints. 

Without this functionality, there's no current way using / testing out the IPFS filestore functionality.

**Comment by alanshaw** [comment] 2019-11-19 13:10
dupe of https://github.com/ipfs/js-ipfs-http-client/issues/963

**Closed by alanshaw** 2019-11-19 13:10 UTC
